import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

const Home = () => {

  const [users, setUsers] = useState({})

  const fetchData = async () => {
    try {
      const response = await fetch('/api/users')
     
      if(response.status === 200) {
        const data = await response.json()
        setUsers(data)
      }
      
    } catch (error) {
      console.error(error.message)
    }
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Landing Page</h1>
        
        <button onClick={() => fetchData()}>Return DB data</button>

        <pre>{JSON.stringify(users, null, 2)}</pre>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home